server.port=8080

# Spring Data JPA & H2 SQL Database Setup (Persistent File Storage)
spring.datasource.url=jdbc:h2:file:./data/swagroohadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.swagrooha=DEBUG

# Razorpay Credentials (Test Mode)
# Replace these with real credentials in production
razorpay.key.id=rzp_test_TNGuNg9TsCrgxS
razorpay.key.secret=DWd93GhUM4TSKWukxJntyb7W
